{
 "title": "Mongodb Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_server_duration_bucket{le=\"0.025\",status=~\"^2..$\", job=\"nestjs-mongodb\"}[1m]))\n+\n  sum(rate(http_server_duration_bucket{le=\"0.1\",status=~\"^2..$\", job=\"nestjs-mongodb\"}[1m]))\n) / 2 / sum(rate(http_server_duration_count{job=\"nestjs-mongodb\"}[1m]))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum(irate(http_server_duration_bucket{le=\"0.025\",status=~\"^2..$\", job=\"nestjs-mongodb\"}[1m]))\n+\n  (sum(irate(http_server_duration_bucket{le=\"0.1\",status=~\"^2..$\", job=\"nestjs-mongodb\"}[1m]))/2)\n) / sum(irate(http_server_duration_count{job=\"nestjs-mongodb\"}[1m]))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Http Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_duration_bucket{job=\"nestjs-mongodb\"}[1m])) by (le,method,path)) * 1000",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "Historic P50 response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{job=\"nestjs-mongodb\"}[1m])) by (le,method,path)) * 1000",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status,method) (increase(http_server_duration_count{job=\"nestjs-mongodb\"}[$__rate_interval]))",
     "legendFormat": "{{method}}: {{status}} status"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (increase(http_server_duration_count{job=\"nestjs-mongodb\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"nestjs-mongodb\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_sum{job=\"nestjs-mongodb\"}[1m])) * 10\n/\nsum(rate(http_server_duration_count{job=\"nestjs-mongodb\"}[1m])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{status=~\"[45]..\", job=\"nestjs-mongodb\"}[1m])) by (job) / sum(rate(http_server_duration_count{job=\"nestjs-mongodb\"}[1m])) by (job)",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"nestjs-mongodb\"}[1m])) by (job)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate(http_server_duration_count{status=\"500\", job=\"nestjs-mongodb\"}[1m])) by (job)",
     "legendFormat": "error responses rate"
    }
   ]
  }
 ]
}